[web]
  title = "APITeam"
  host = "${WEB_HOST}"
  port = "${WEB_PORT}"
  apiUrl = "/api"
  includeEnvironmentVariables = []
[api]
  port = "${API_PORT}"
  host = "${API_HOST}"
[browser]
  open = false
