version: '2'

services:
  redis-scopes:
    image: docker.io/bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6377:6379'
    volumes:
      - 'redis_scopes_data:/bitnami/redis/data'
  redis-orchestrator:
      image: docker.io/bitnami/redis:7.0
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      ports:
        - '6378:6379'
      volumes:
        - 'redis_orchestrator_data:/bitnami/redis/data'
  redis-worker:
    image: docker.io/bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'redis_worker_data:/bitnami/redis/data'

volumes:
  redis_scopes_data:
    driver: local
  redis_orchestrator_data:
    driver: local
  redis_worker_data:
    driver: local