export const ROUTES = {
  root: '/',
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  userUnsubscribe: '/user-unsubscribe',
  blanketUnsubscribe: '/blanket-unsubscribe',
  whyAPITeam: '/platform/why-apiteam',
  pricing: '/platform/pricing',
  about: '/company/about',
  contact: '/contact',
  termsOfService: '/legal/terms-of-service',
  privacyPolicy: '/legal/privacy-policy',
  cookiePolicy: '/legal/cookie-policy',
  supportCenter: '/support',
  docs: '/docs',
  blog: '/blog',
  dashboard: '/app/dashboard',
  settingsWorkspace: '/app/dashboard/settings',
  settingsWorkspaceMembers: '/app/dashboard/settings/members',
  domains: '/app/dashboard/domains',
  collectionEditor: '/app/collection',
  admin: '/admin',
  acceptInvitation: '/accept-invitation',
  declineInvitation: '/decline-invitation',
  verifyEmail: '/verify-email',
} as const
